//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PorpoiseMobileApp {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("PorpoiseMobileApp.Resource", typeof(Resource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string AccessRequiredTitle {
            get {
                return ResourceManager.GetString("AccessRequiredTitle", resourceCulture);
            }
        }
        
        public static string AccountDoesNotExistError {
            get {
                return ResourceManager.GetString("AccountDoesNotExistError", resourceCulture);
            }
        }
        
        public static string Activity {
            get {
                return ResourceManager.GetString("Activity", resourceCulture);
            }
        }
        
        public static string Challenges {
            get {
                return ResourceManager.GetString("Challenges", resourceCulture);
            }
        }
        
        public static string AllowCamera {
            get {
                return ResourceManager.GetString("AllowCamera", resourceCulture);
            }
        }
        
        public static string AllowPhotoAccess {
            get {
                return ResourceManager.GetString("AllowPhotoAccess", resourceCulture);
            }
        }
        
        public static string ArchivedActivity {
            get {
                return ResourceManager.GetString("ArchivedActivity", resourceCulture);
            }
        }
        
        public static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        public static string Camera {
            get {
                return ResourceManager.GetString("Camera", resourceCulture);
            }
        }
        
        public static string CameraAccessRequiredMessage {
            get {
                return ResourceManager.GetString("CameraAccessRequiredMessage", resourceCulture);
            }
        }
        
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        public static string ChooseFromLibrary {
            get {
                return ResourceManager.GetString("ChooseFromLibrary", resourceCulture);
            }
        }
        
        public static string ChooseImageSourceMessage {
            get {
                return ResourceManager.GetString("ChooseImageSourceMessage", resourceCulture);
            }
        }
        
        public static string ClickHereToJoin {
            get {
                return ResourceManager.GetString("ClickHereToJoin", resourceCulture);
            }
        }
        
        public static string CompanyWide {
            get {
                return ResourceManager.GetString("CompanyWide", resourceCulture);
            }
        }
        
        public static string CompanyWideIndividualSentence {
            get {
                return ResourceManager.GetString("CompanyWideIndividualSentence", resourceCulture);
            }
        }
        
        public static string CompanyWideGroupSentence {
            get {
                return ResourceManager.GetString("CompanyWideGroupSentence", resourceCulture);
            }
        }
        
        public static string DeletePost {
            get {
                return ResourceManager.GetString("DeletePost", resourceCulture);
            }
        }
        
        public static string Dismiss {
            get {
                return ResourceManager.GetString("Dismiss", resourceCulture);
            }
        }
        
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        public static string EditPost {
            get {
                return ResourceManager.GetString("EditPost", resourceCulture);
            }
        }
        
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        public static string EmailSentMessage {
            get {
                return ResourceManager.GetString("EmailSentMessage", resourceCulture);
            }
        }
        
        public static string EndDateSentence {
            get {
                return ResourceManager.GetString("EndDateSentence", resourceCulture);
            }
        }
        
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        public static string Gallery {
            get {
                return ResourceManager.GetString("Gallery", resourceCulture);
            }
        }
        
        public static string GetPostDetailsError {
            get {
                return ResourceManager.GetString("GetPostDetailsError", resourceCulture);
            }
        }
        
        public static string GoalProgressSentence {
            get {
                return ResourceManager.GetString("GoalProgressSentence", resourceCulture);
            }
        }
        
        public static string HoursLoggedError {
            get {
                return ResourceManager.GetString("HoursLoggedError", resourceCulture);
            }
        }
        
        public static string HoursLoggedSuccess {
            get {
                return ResourceManager.GetString("HoursLoggedSuccess", resourceCulture);
            }
        }
        
        public static string HoursUpdatedError {
            get {
                return ResourceManager.GetString("HoursUpdatedError", resourceCulture);
            }
        }
        
        public static string HoursUpdatedSuccess {
            get {
                return ResourceManager.GetString("HoursUpdatedSuccess", resourceCulture);
            }
        }
        
        public static string ImageRotationError {
            get {
                return ResourceManager.GetString("ImageRotationError", resourceCulture);
            }
        }
        
        public static string InactiveGoalError {
            get {
                return ResourceManager.GetString("InactiveGoalError", resourceCulture);
            }
        }
        
        public static string InvalidDateError {
            get {
                return ResourceManager.GetString("InvalidDateError", resourceCulture);
            }
        }
        
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        public static string InvalidFieldsError {
            get {
                return ResourceManager.GetString("InvalidFieldsError", resourceCulture);
            }
        }
        
        public static string InvalidGoalError {
            get {
                return ResourceManager.GetString("InvalidGoalError", resourceCulture);
            }
        }
        
        public static string InvalidHourAmountError {
            get {
                return ResourceManager.GetString("InvalidHourAmountError", resourceCulture);
            }
        }
        
        public static string InvalidOrganizationError {
            get {
                return ResourceManager.GetString("InvalidOrganizationError", resourceCulture);
            }
        }
        
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        public static string InviteCorworkerMessage {
            get {
                return ResourceManager.GetString("InviteCorworkerMessage", resourceCulture);
            }
        }
        
        public static string LeavingPorpoiseWarning {
            get {
                return ResourceManager.GetString("LeavingPorpoiseWarning", resourceCulture);
            }
        }
        
        public static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        public static string LoginFailedTitle {
            get {
                return ResourceManager.GetString("LoginFailedTitle", resourceCulture);
            }
        }
        
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        public static string MailNotOnError {
            get {
                return ResourceManager.GetString("MailNotOnError", resourceCulture);
            }
        }
        
        public static string MissingUploadedImage {
            get {
                return ResourceManager.GetString("MissingUploadedImage", resourceCulture);
            }
        }
        
        public static string NewOrganization {
            get {
                return ResourceManager.GetString("NewOrganization", resourceCulture);
            }
        }
        
        public static string NewOrganizationMessage {
            get {
                return ResourceManager.GetString("NewOrganizationMessage", resourceCulture);
            }
        }
        
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        public static string NoPostToDisplayMessage {
            get {
                return ResourceManager.GetString("NoPostToDisplayMessage", resourceCulture);
            }
        }
        
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        public static string Oops {
            get {
                return ResourceManager.GetString("Oops", resourceCulture);
            }
        }
        
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        public static string PhotosAccessRequiredMessage {
            get {
                return ResourceManager.GetString("PhotosAccessRequiredMessage", resourceCulture);
            }
        }
        
        public static string PickImage {
            get {
                return ResourceManager.GetString("PickImage", resourceCulture);
            }
        }
        
        public static string PorpoiseConnectionError {
            get {
                return ResourceManager.GetString("PorpoiseConnectionError", resourceCulture);
            }
        }
        
        public static string Post {
            get {
                return ResourceManager.GetString("Post", resourceCulture);
            }
        }
        
        public static string PostDonationSentence {
            get {
                return ResourceManager.GetString("PostDonationSentence", resourceCulture);
            }
        }
        
        public static string Posted {
            get {
                return ResourceManager.GetString("Posted", resourceCulture);
            }
        }
        
        public static string PostedIndividualSentence {
            get {
                return ResourceManager.GetString("PostedIndividualSentence", resourceCulture);
            }
        }
        
        public static string PostedGroupSentence {
            get {
                return ResourceManager.GetString("PostedGroupSentence", resourceCulture);
            }
        }
        
        public static string ProblemOccurred {
            get {
                return ResourceManager.GetString("ProblemOccurred", resourceCulture);
            }
        }
        
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        public static string Reward {
            get {
                return ResourceManager.GetString("Reward", resourceCulture);
            }
        }
        
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        public static string TypeSentence {
            get {
                return ResourceManager.GetString("TypeSentence", resourceCulture);
            }
        }
        
        public static string Progress {
            get {
                return ResourceManager.GetString("Progress", resourceCulture);
            }
        }
        
        public static string RetrieveProfileError {
            get {
                return ResourceManager.GetString("RetrieveProfileError", resourceCulture);
            }
        }
        
        public static string S3BucketName {
            get {
                return ResourceManager.GetString("S3BucketName", resourceCulture);
            }
        }
        
        public static string S3KeyNameEnd {
            get {
                return ResourceManager.GetString("S3KeyNameEnd", resourceCulture);
            }
        }
        
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        public static string ServerConnectionError {
            get {
                return ResourceManager.GetString("ServerConnectionError", resourceCulture);
            }
        }
        
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        public static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        public static string ConfirmationCodeMessage {
            get {
                return ResourceManager.GetString("ConfirmationCodeMessage", resourceCulture);
            }
        }
        
        public static string ConfirmationCodeError {
            get {
                return ResourceManager.GetString("ConfirmationCodeError", resourceCulture);
            }
        }
        
        public static string SupportEmailAddress {
            get {
                return ResourceManager.GetString("SupportEmailAddress", resourceCulture);
            }
        }
        
        public static string SupportEmailBody {
            get {
                return ResourceManager.GetString("SupportEmailBody", resourceCulture);
            }
        }
        
        public static string SupportEmailError {
            get {
                return ResourceManager.GetString("SupportEmailError", resourceCulture);
            }
        }
        
        public static string SupportEmailSentMessage {
            get {
                return ResourceManager.GetString("SupportEmailSentMessage", resourceCulture);
            }
        }
        
        public static string SupportEmailSentTitle {
            get {
                return ResourceManager.GetString("SupportEmailSentTitle", resourceCulture);
            }
        }
        
        public static string SupportEmailSubject {
            get {
                return ResourceManager.GetString("SupportEmailSubject", resourceCulture);
            }
        }
        
        public static string TakePhoto {
            get {
                return ResourceManager.GetString("TakePhoto", resourceCulture);
            }
        }
        
        public static string UnknownViewModel {
            get {
                return ResourceManager.GetString("UnknownViewModel", resourceCulture);
            }
        }
        
        public static string UnsavedChanges {
            get {
                return ResourceManager.GetString("UnsavedChanges", resourceCulture);
            }
        }
        
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        public static string UploadAnImage {
            get {
                return ResourceManager.GetString("UploadAnImage", resourceCulture);
            }
        }
        
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
