// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace PorpoiseMobileApp.iOS
{
	public partial class LogHoursViewController : MvvmViewController<ViewModels.LogHoursViewModel>
	{


	}
}
