// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace PorpoiseMobileApp.iOS {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("PorpoiseMobileApp.iOS.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Activity {
            get {
                return ResourceManager.GetString("Activity", resourceCulture);
            }
        }
        
        internal static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        internal static string ClickHereToJoin {
            get {
                return ResourceManager.GetString("ClickHereToJoin", resourceCulture);
            }
        }
        
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        internal static string EmailSentMessage {
            get {
                return ResourceManager.GetString("EmailSentMessage", resourceCulture);
            }
        }
        
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        internal static string GetPostDetailsError {
            get {
                return ResourceManager.GetString("GetPostDetailsError", resourceCulture);
            }
        }
        
        internal static string HoursLoggedError {
            get {
                return ResourceManager.GetString("HoursLoggedError", resourceCulture);
            }
        }
        
        internal static string HoursLoggedSuccess {
            get {
                return ResourceManager.GetString("HoursLoggedSuccess", resourceCulture);
            }
        }
        
        internal static string HoursUpdatedError {
            get {
                return ResourceManager.GetString("HoursUpdatedError", resourceCulture);
            }
        }
        
        internal static string HoursUpdatedSuccess {
            get {
                return ResourceManager.GetString("HoursUpdatedSuccess", resourceCulture);
            }
        }
        
        internal static string ImageRotationError {
            get {
                return ResourceManager.GetString("ImageRotationError", resourceCulture);
            }
        }
        
        internal static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        internal static string InvalidFieldsError {
            get {
                return ResourceManager.GetString("InvalidFieldsError", resourceCulture);
            }
        }
        
        internal static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        internal static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        internal static string MailNotOnError {
            get {
                return ResourceManager.GetString("MailNotOnError", resourceCulture);
            }
        }
        
        internal static string MailNotOnTitle {
            get {
                return ResourceManager.GetString("MailNotOnTitle", resourceCulture);
            }
        }
        
        internal static string MissingUploadedImage {
            get {
                return ResourceManager.GetString("MissingUploadedImage", resourceCulture);
            }
        }
        
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        internal static string Post {
            get {
                return ResourceManager.GetString("Post", resourceCulture);
            }
        }
        
        internal static string PostDonationSentence {
            get {
                return ResourceManager.GetString("PostDonationSentence", resourceCulture);
            }
        }
        
        internal static string ProblemOccurred {
            get {
                return ResourceManager.GetString("ProblemOccurred", resourceCulture);
            }
        }
        
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        internal static string S3BucketName {
            get {
                return ResourceManager.GetString("S3BucketName", resourceCulture);
            }
        }
        
        internal static string S3KeyNameEnd {
            get {
                return ResourceManager.GetString("S3KeyNameEnd", resourceCulture);
            }
        }
        
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        internal static string ServerConnectionError {
            get {
                return ResourceManager.GetString("ServerConnectionError", resourceCulture);
            }
        }
        
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        internal static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        internal static string SupportEmailAddress {
            get {
                return ResourceManager.GetString("SupportEmailAddress", resourceCulture);
            }
        }
        
        internal static string SupportEmailBody {
            get {
                return ResourceManager.GetString("SupportEmailBody", resourceCulture);
            }
        }
        
        internal static string SupportEmailError {
            get {
                return ResourceManager.GetString("SupportEmailError", resourceCulture);
            }
        }
        
        internal static string SupportEmailSent {
            get {
                return ResourceManager.GetString("SupportEmailSent", resourceCulture);
            }
        }
        
        internal static string SupportEmailSubject {
            get {
                return ResourceManager.GetString("SupportEmailSubject", resourceCulture);
            }
        }
        
        internal static string UnknownViewModel {
            get {
                return ResourceManager.GetString("UnknownViewModel", resourceCulture);
            }
        }
        
        internal static string ConfirmationCodeError {
            get {
                return ResourceManager.GetString("ConfirmationCodeError", resourceCulture);
            }
        }
        
        internal static string UnsavedChanges {
            get {
                return ResourceManager.GetString("UnsavedChanges", resourceCulture);
            }
        }
    }
}
